### ISSUE TITLE
Specifying unlimited cost of resolution

### ISSUE THREAD

**Issue by amoe** [xsc/claro#12]
More of a question than an issue really but I would like to be able to specify that resolution should never fail due to the cost of a batch.  It seems that `:max-cost` does not support any way to specify this (although maybe one of the Java infinities would work?)

Also, it's possible that wanting to do this is wrong in the first place.  I would be interested to know more about how the cost concept is supposed to be used.  In my case, the number of Resolvables is related to database rows in a `xn` fashion (say `x = 3` resolvables produced per database row, and `n` database rows), but since the `n` is variable I could never fix a static `:max-cost` without counting the rows first.

**Comment by xsc** [comment]
@amoe Great questions! To answer your first one, I'm pretty sure Java infinities would work here. But I'll still add a `:check-cost?` flag to the engine options to have an explicit way of disabling it.

> In my case, the number of Resolvables is related to database rows in a xn fashion (say x = 3 resolvables produced per database row, and n database rows), but since the n is variable I could never fix a static :max-cost without counting the rows first.

The cost value should be a relative measure of query complexity between different resolvables. For example, a batched lookup by ID will almost certainly be cheaper than querying a sorted, paginated list of entities. Or a non-batched lookup by ID, for that matter. This is reflected in the default cost behaviour:

- the cost is `0` for `PureResolvable` values,
- the cost is `1` for batches of `BatchedResolvable` values,
- the cost is `n` for batches of size `n` of `Resolvable` values.

I'm operating under the assumption that the potential number of results does not contribute to the resolution cost as significantly as the type of query and number of input resolvables, since the "heavy lifting" (as in filtering, sorting, joining) has already be done at that point and only I/O remains to get the results from the datastore into the application.

But if you want to take the potential number of results into account, you can do a worst-case estimate rather easily:

- for simple lookups, use the input batch size (see the second parameter of `cost`) as your factor,
- for list queries you could use a `:limit` field in your resolvable (which is a good idea anyways to avoid fetching the whole world within one query).

Hope that helps!

**Comment by amoe** [comment]
Thanks for this!  :)

**Comment by xsc** [comment]
[Release 0.2.20](https://github.com/xsc/claro/releases/tag/v0.2.20)
