### ISSUE TITLE
Caching Middleware

### ISSUE THREAD

**Issue by jcf** [xsc/claro#9]
Hi Yannick,

I was having a quick look through Claro, and wondered if you have plans to open up the caching strategy (currently you're using an in-memory, transient hash-map I believe).

If I have a couple of JVMs fetching data it would be useful if they could both share the work they're doing via something like Redis or Memcached. Obviously, Clojurescript users in a browser environment won't be hitting up Redis, but in a backend service this could be quite useful.

Maybe a protocol so I can implement my own external caching strategy on top of Redis?

Thanks for open sourcing Claro!

P.S. I guess with Onyx mentioning you in their docs you may get a few questions like mine.

**Comment by xsc** [comment]
Hi James,

the internal cache (the one based on the in-memory, transient hash-map) is intended to ensure consistency within a single engine run – i.e., if one is fetching `(->Person 1)` in multiple places (and maybe not at the same time) there should always be the same result. If this cache was accessible by multiple threads or JVMs you might not have this guarantee (unless a data structure with snapshot capabilities is used). So, for that one I'm not sure it makes sense to have it pluggable.

But if your goal is having an additional caching layer between claro and any data sources you are accessing, that's a different story. In fact, this has been planned since the very beginning which is why claro offers the possibility to wrap resolution using [middlewares](https://github.com/xsc/claro/blob/master/doc/03-engine.md#middlewares).

It should be relatively straightforward to implement a caching middleware with pluggable datastore implementations (e.g, as you mentioned, behind a protocol). It would:

- query the cache for all resolvables in the current batch,
- use the actual resolver function to fetch all elements not found in the cache,
- write resolution results back to the cache,
- merge the cached and uncached results.

So, the cache protocol might really just consist of `fetch-from-cache!` and `write-to-cache!`.

This _will_ be added – I just haven't gotten to it yet. :) But if you or anyone else would like to tackle the issue I'll be more than happy to help with any surfacing problems. :)

**Comment by xsc** [comment]
[Release 0.2.20](https://github.com/xsc/claro/releases/tag/v0.2.20)

This contains the basic cache middleware, no implementations yet. But anyone that wants to tackle this, feel free to. :) I'm planning to have at least an in-memory implementation based on `core.cache`, as well as one based on Redis .
